language: ruby
sudo: false
cache: bundler
script: ./script/ci
rvm:
  - 2.3.6
  - 2.4.2
  - 2.5.0
  - ruby-head
  - jruby-9.1.16.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
